# Generated by Django 4.2.2 on 2023-07-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hm_cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelCars',
            new_name='CarModel',
        ),
    ]
