# Generated by Django 4.2.2 on 2023-07-04 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
