# Generated by Django 4.2.2 on 2023-07-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_parks1', '0001_initial'),
        ('cars1', '0002_carsmodel_created_at_carsmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsmodel',
            name='auto_park',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='auto_parks1.autoparkmodel'),
            preserve_default=False,
        ),
    ]
