# Generated by Django 4.2.2 on 2023-06-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hm_cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelcars',
            table='hm_cars',
        ),
    ]
